dependencies {
    implementation project(':config')
    implementation project(':domain')
    implementation project(':adapter')
    implementation project(':service')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation platform('org.junit:junit-bom:5.11.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
